id: P2E88BAA0
initial_creation_type: input
source_metadata:
  title: Sang Offering
  language: zh
  description: 'Texts on the subject of Sang (bsang/bsangs) or Purificatory Incense
    Smoke Offering:'
  volume:
    136a5573a0da4fbe8b6f9ea1858d1d93:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    9475f505acac4d66bcde27c7bb793f43:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    f025b30fe9fd49fabd94156f2535dcf8:
      title: Yarlha Shampo Sang Offering
      parent: Dharma Protectors
    8b76d7f50ca5484cbf91a4c2c02914c4:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    85f5da3affda4efab17895822753ea2a:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    dd729cee4dcc4373a545b60a2e1ebe49:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Rituals
    d435c9872fc64540bfc105078eae6fc5:
      title: Sang Offering to Yellow Jambhala
      parent: Rituals
    828b83a5091943418244650f6d6e999f:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Rituals
    947fb02628b24cc596d0d22c0fb46aee:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Rituals
    e56514b55cf3429291c0aaf7bd30ef13:
      title: Brief Sang Offering
      parent: Rituals
    9602aae15d37484cb2f13cf53fea6871:
      title: Brief Sang Offering to Purify Contamination
      parent: Rituals
    4d714c146cb34cc5b0af36d64d387623:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Rituals
    f7764057fd0c4b1c8ea522c58137c44b:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Riwo Sangchö
    aa79467692ba4381a550d3be611b9189:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Riwo Sangchö
    6ae49cbd77614d1a9f664d9218434477:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Riwo Sangchö
    597604c74d4e42528235c0934b2e8c18:
      title: A Concise Sang Offering to Tārā
      parent: Tārā
created_at: '2022-03-01T05:40:37.294859'
last_modified_at: '2022-03-01T05:40:37.294861'
